### PR TITLE
Improve full-migrate

### LINKED ISSUE #10: [Bug] Error message generation of `fullMigrate` is raising an exception
When the `fullMigrate` command is running, if it encounters an error it tries to generate a message.  The generation of that message seems to have a bug that's causing an exception.  

In particular I see this when it errors out during the duplicate cleanup/detection.  

In the following, `/mnt` is the root of my Takeout folder.

```
[...snip...]
Done! Processed 11256 files.
Files migrated: 11150
Files failed: 106
Rewriting all tags from /mnt/Google Photos/PhotosError/original_8785a13f-e6d2-45ce-a096-0c237dad625e_2(1).jpg, to  /mnt/Google Photos/Photos/cleaned-original_8785a13f-e6d2-45ce-a096-0c237dad625e_2(1).jpg
Cannot fix metadata for /mnt/Google Photos/PhotosError/iMarkup_20190704_122554.png.json as .json is an unsupported file type.
Rewriting all tags from /mnt/Google Photos/PhotosError/iMarkup_20190704_122554.png, to  /mnt/Google Photos/Photos/cleaned-iMarkup_20190704_122554.png
Rewriting all tags from /mnt/Google Photos/PhotosError/duplicates-2, to  /mnt/Google Photos/Photos/cleaned-duplicates-2
/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:41
                    error = new Error(errMsg);
                            ^

Error: '/mnt/Google Photos/Photos/cleaned-duplicates-2' already exists - /mnt/Google Photos/PhotosError/duplicates-2/20230224_131215.jpg
    at RewriteAllTagsTask.parser (/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:41:29)
    at RewriteAllTagsTask._Task_resolve (/app/node_modules/batch-cluster/dist/Task.js:146:40)

Node.js v18.13.0
error Command failed with exit code 1.
```

It appears that it encountered some error, but then the attempt to generate the error message itself has an error:
```
/app/node_modules/exiftool-vendored/dist/ExifToolTask.js:41
                    error = new Error(errMsg);
                            ^
```

### PR DESCRIPTION
**Pull request by lukehmcc**
Improvements:
- Requires user to specify output directory for `fullMigrate`. It will now no longer mess with the Takeout dir at all. No restructure, no folder creation. 
- Restructure step has been removed. Instead of organizing the folders and then running the migration code, the migration code is just called directly.
- Handling files that need their metadata forcefully rewritten has been improved. It will no longer reprocess tens of thousands of photos just because a single one in that folder was malformed. This fixes #10. 
- Remove all sync calls so it can be better integrated into other code once it's listed on npm.
- Updates exports & their naming.

### CODE REVIEW

**Comment by mtalexan** [comment]
The counter for the migration doesn't seem to be getting populated.  After every directory it always lists 0 files processed, migrated, and failed.

```
Done! Processed 0 files.
Files migrated: 0
Files failed: 0
```

**Comment by mtalexan** [comment]
Also, as you iterate thru the Takeout folders, you're reprocessing the entire `PhotosError` folder after each one if there were any files added to it from the Takeout folder being processed. If there were photos added to the `PhotosError` folder during processing of the first Takeout folder, those then get re-processed on every subsequent Takeout folder processing that has errors as well.

I think you want to only process the `PhotosError` folder once after you've processed all the Takeout folders, don't you?  If you're unable to fix any images in the `PhotosError` (which is likely), they'll just stay in that folder so you're probably better off just doing it once at the very end.

**Comment by mtalexan** [comment]
You don't appear to be filtering the file extensions when processing `PhotosError` either.  It's trying to process JSON sidecar files when it tries to address the images in `PhotosError`, producing output like the following:
```
Cannot fix metadata for /output/PhotosError/20210918_123441.jpg.json as .json is an unsupported file type.
Cannot fix metadata for /output/PhotosError/20210918_123441.jpg(1).json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/20210918_123441.jpg
Cannot fix metadata for /output/PhotosError/20210918_120622.jpg.json as .json is an unsupported file type.
Cannot fix metadata for /output/PhotosError/20210918_120622.jpg(1).json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/20210918_120622.jpg
Cannot fix metadata for /output/PhotosError/20210627_135434_04.mp4.json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/20210627_135434_04.mp4
Cannot fix metadata for /output/PhotosError/20210627_134405_10.mp4.json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/20210627_134405_10.mp4
Cannot fix metadata for /output/PhotosError/2021-08-13 19.01.07.png.json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/2021-08-13 19.01.07.png
Cannot fix metadata for /output/PhotosError/2021-08-08 10.30.36.png.json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/2021-08-08 10.30.36.png
Cannot fix metadata for /output/PhotosError/2021-08-02 22.37.37.png.json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/2021-08-02 22.37.37.png
Cannot fix metadata for /output/PhotosError/2021-07-26 22.42.40.png.json as .json is an unsupported file type.
File already exists (you can ignore this): /output/PhotosError/2021-07-26 22.42.40.png
```

**Comment by lukehmcc** [comment]
> The counter for the migration doesn't seem to be getting populated. After every directory it always lists 0 files processed, migrated, and failed.
> 
> ```
> Done! Processed 0 files.
> Files migrated: 0
> Files failed: 0
> ```

This is a known issue, I pushed the latest commit so @garzj could take a look at it as I was struggling to find the issue.

**Comment by lukehmcc** [comment]
> You don't appear to be filtering the file extensions when processing `PhotosError` either. It's trying to process JSON sidecar files when it tries to address the images in `PhotosError`, producing output like the following:
> 
> ```
> Cannot fix metadata for /output/PhotosError/20210918_123441.jpg.json as .json is an unsupported file type.
> Cannot fix metadata for /output/PhotosError/20210918_123441.jpg(1).json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/20210918_123441.jpg
> Cannot fix metadata for /output/PhotosError/20210918_120622.jpg.json as .json is an unsupported file type.
> Cannot fix metadata for /output/PhotosError/20210918_120622.jpg(1).json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/20210918_120622.jpg
> Cannot fix metadata for /output/PhotosError/20210627_135434_04.mp4.json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/20210627_135434_04.mp4
> Cannot fix metadata for /output/PhotosError/20210627_134405_10.mp4.json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/20210627_134405_10.mp4
> Cannot fix metadata for /output/PhotosError/2021-08-13 19.01.07.png.json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/2021-08-13 19.01.07.png
> Cannot fix metadata for /output/PhotosError/2021-08-08 10.30.36.png.json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/2021-08-08 10.30.36.png
> Cannot fix metadata for /output/PhotosError/2021-08-02 22.37.37.png.json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/2021-08-02 22.37.37.png
> Cannot fix metadata for /output/PhotosError/2021-07-26 22.42.40.png.json as .json is an unsupported file type.
> File already exists (you can ignore this): /output/PhotosError/2021-07-26 22.42.40.png
> ```

I think this is just confusing logging. It *isn't* processing `*.json` files. It tells the user when it doesn't process them which it probably shouldn't
```ts 
for (let file of errFiles) {
      if (file.endsWith('.json')) {
        console.log(
          `Cannot fix metadata for ${file} as .json is an unsupported file type.`
        );
        continue;
...
```

**Comment by lukehmcc** [comment]
> Also, as you iterate thru the Takeout folders, you're reprocessing the entire `PhotosError` folder after each one if there were any files added to it from the Takeout folder being processed. If there were photos added to the `PhotosError` folder during processing of the first Takeout folder, those then get re-processed on every subsequent Takeout folder processing that has errors as well.
> 
> I think you want to only process the `PhotosError` folder once after you've processed all the Takeout folders, don't you? If you're unable to fix any images in the `PhotosError` (which is likely), they'll just stay in that folder so you're probably better off just doing it once at the very end.

Should be fixed now. Pushed the error checking up the chain so it should only check after items have been processed.

**Comment by garzj** [comment]
> The counter for the migration doesn't seem to be getting populated. After every directory it always lists 0 files processed, migrated, and failed.
> 
> ```
> Done! Processed 0 files.
> Files migrated: 0
> Files failed: 0
> ```

Yes, it was just the counter, I pushed a fix.

**Pull request merged**
