### PR TITLE
Added spanish language

### PR DESCRIPTION
**Pull request by d4f0**
Added spanish language suffice.
Spanish dir already exists (Google Fotos).

### CODE REVIEW

**Comment by garzj** [comment]
Thank you! What about the `Untitled` directory? Do you have one?

**Comment by d4f0** [comment]
Unfortunately there is no `Untitled` dir in my export. I'm not sure which name it may have.

**Comment by d4f0** [comment]
I think the `Untitled` dir may not be translated at all. The directories generated by Google are all in English. I have directories named Photos from _"year"_ and Failed videos. 

The only directories in Spanish are the ones that take the name of manually created albums.

**Comment by garzj** [comment]
Hmm, at least in my case there were directories called `Unbenannt` (German) and some more `Unbenannt(1)`, `Unbenannt(2)` and so on. The tool just tries to group them back together cause there were so many.
I don't really know either how and why they're generated, so you may be right that it has nothing to do with Google Photos. I suspect that the other language PRs added the translations for a reason though.

**Pull request merged**
